FROM dietergribnitz/dockerstack:server

RUN apt-get -y install net-tools
RUN apt-get -y install debhelper
RUN apt-get -y install golang-1.10
RUN apt-get -y install jq
RUN apt-get -y install dpkg-dev
RUN apt-get -y install htop
RUN apt-get -y install traceroute
#RUN apt-get -y install smartmontools
#RUN apt-get -y install webmin


